dataType: postgres

pathToData:
  pguser: 'pipable'
  pgpass: 'pipable'
  pghost: '34.82.20.16'
  pgdata: 'postgres'
  pgsche: 'alyf'
  pgport: 5432

keys:
  openAI: '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'
  google: 'AIzaSyB88bY1dmo50Pp9dSTzln-JqhsfV_CSW2o'
  search_engine: '336ee76d0d6af4acd'

action_desc:
  llm: "ask LLm: for answers on health related questions or table description.Ask LLM."
  llm_google: "search+LLM : ask LLM for answer on health related questions and get reference link from internet or google"
  find_similar_score: "find cosine similarity or similarity score between query and key vectors"
  create_key_vectors: "update the semantic search module with text list"
  vectorize: "generate vectors or embeddings for a list of text documents or sentences"
  google_search: "query google to find answers to certain questions"
  data_search: "search the table or or database for information on patients"
  read_csv: "read csv file. read csv."
  read_parquet: "read parquet file. read parquet."
  read_pdf: "read pdf file. read pdf."

context:
  heart failure risk: "HFI greater than 35 is a heart failure risk."
  heart stroke risk: "Blood pressure greater than 120 is a risk to heart."