dataType: postgres

pathToData:
  pguser: 'pipable'
  pgpass: 'pipable'
  pghost: '34.82.20.16'
  pgdata: 'postgres'
  pgsche: 'alyf'
  pgport: 5432

keys:
  openAI: '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'
  google: 'AIzaSyB88bY1dmo50Pp9dSTzln-JqhsfV_CSW2o'
  search_engine: '336ee76d0d6af4acd'

action_desc:
  ada: "Ask LLM. What leads to X. What leads to Y. Hi Ada let me know what is X. LLM based query. Open ai tell me why a happens."
  semantic_search: "Perform semantic search given a query. Queries can be like find similar items"
  google_search: "Query google to find answers to certain questions. Can you use google to get me the results, look at google , get search results , get reference links, do google search."
  data_search: "Look in the table. Look in csv file. Evaluate the table. Find in table. Resolve dataframe . Write code to extract. Write queries to. Show me the results of a particular entity. Get me the list of entities where val > X. Analyse the data in a particular time period."

schema:
  alyf_asvs:
    keys:
      - "cardio_recovery_time_daily_avg"
      - "timestamp"
      - "heart_rate_daily_avg"
      - "heart_rate_daily_max"
      - "weight_daily_avg"
      - "hrv_daily_min"
      - "spo2_daily_avg"
      - "breathing_rate_daily_avg"
      - "sleep_duration_total_daily_sum"
      - "hypnogram_daily_avg"
      - "step_count_daily_max"
      - "vo2_max_daily_max"
      - "weight_daily_avg_1d_delta_v"
      - "weight_daily_avg_3d_delta_v"
      - "weight_daily_avg_7d_delta_v"
      - "weight_daily_avg_90d_delta_v"
      - "daily_hfi"
      - "mindfulness_minutes_daily_sum"
      - "bp_systolic_daily_max"
      - "bp_systolic_daily_avg"
      - "bp_diastolic_daily_avg"
      - "bp_diastolic_daily_min"
      - "idling_heart_rate_daily_avg"
      - "idling_heart_rate_daily_max"
      - "member_id"
    dataTypes:
      - "double precision"
      - "timestamp with time zone"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "character varying"
    descriptors:
      - "Cardio Recovery or heart rate recovery of 13 or greater (meaning a drop of 13 bpm or more) after 1 minute, or 22 or greater after two minutes is in the normal/healthy range."
      - "Time when the events in this table have taken place"
      - " the range for most healthy adults is between 55 and 85 beats per minute"
      - "To estimate your maximum age-related heart rate, subtract your age from 220. For example, for a 50-year-old person, the estimated maximum age-related heart rate would be calculated as 220 - 50 years = 170 beats per minute (bpm)"
      - "increases of more than 2 and up to 5 pounds, more than 5 and up to 10 pounds, and more than 10 pounds (relative to time of enrollment in the monitoring system) were associated with matched adjusted odds ratios for heart failure hospitalization of 2.77 (95% confidence interval 1.13 to 6.80), 4.46 (95% confidence interval 1.45 to 13.75), and 7.65 (95% confidence interval 2.22 to 26.39), respectively, compared with mean increases of 2 pounds or less"
      - " Baseline oxygen saturation by pulse oximetry decreased progressively in relation to the presence and the severity of acute heart failure assessed by Killip classes 1 to 3 (mean: 95, 92 and 85, respectively; P<.001) or by radiology score 0 to 4 (95, 94, 92, 89 and 83, respectively; P<.001), with a correlation coefficient of 0.66 and 0.63, respectively."
      - "Blood oxygen level usually range from 75-100 mm Hg. If they fall below 60 mm HgTrusted Source, there may not be enough oxygen reaching the body's vital organs. This can lead to a range of symptoms."
      - "The normal respiratory rate for healthy adults is between 12-20 breaths per minute. At this breathing rate, the carbon dioxide exits the lungs at the same rate that the body produces it. Breathing rates of below 12 or above 20 can mean a disruption in the normal breathing processes."
      - "sleep_duration_total_daily_sum"
      - "hypnogram_daily_avg"
      - "step_count_daily_max"
      - "vo2_max_daily_max"
      - "weight_daily_avg_1d_delta_v"
      - "weight_daily_avg_3d_delta_v"
      - "weight_daily_avg_7d_delta_v"
      - "weight_daily_avg_90d_delta_v"
      - "daily_hfi > 10 points to a ptient at risk. The higher the hfi goes more the patient at risk of heart failure"
      - "mindfulness_minutes_daily_sum"
      - "bp_systolic_daily_max"
      - "bp_systolic_daily_avg"
      - "bp_diastolic_daily_avg"
      - "bp_diastolic_daily_min"
      - "idling_heart_rate_daily_avg"
      - "idling_heart_rate_daily_max"
      - "member_id the id of the patient"
  alyf_members:
    keys:
      - "active"
      - "tryv_info"
      - "create_time"
      - "update_time"
      - "date_of_birth"
      - "synth"
      - "gender"
      - "address"
      - "member_id"
      - "fallback_time_zone"
      - "provider_id"
      - "first_name"
      - "last_name"
      - "email"
      - "tryv_id"
    dataTypes:
      - "boolean"
      - "jsonb"
      - "timestamp with time zone"
      - "timestamp with time zone"
      - "timestamp with time zone"
      - "boolean"
      - "character varying"
      - "character varying"
      - "character varying"
      - "character varying"
      - "character varying"
      - "character varying"
      - "character varying"
      - "character varying"
      - "character varying"
    descriptors:
      - "active"
      - "tryv_info"
      - "create_time"
      - "update_time"
      - "date_of_birth of the person. The column date_of_birth - the column update_time is the age of a person"
      - "synth"
      - "gender of the patient"
      - "address the address of the patient"
      - "member_id the id of the patient"
      - "fallback_time_zone"
      - "provider_id"
      - "first name of the patient"
      - "last name of the patient"
      - "email id of the person. can be fethed if contact details of the person is needed"
      - "tryv_id"