dataType: postgres

pathToData:
  pguser: 'pipable'
  pgpass: 'pipable'
  pghost: '34.82.20.16'
  pgdata: 'postgres'
  pgsche: 'alyf'
  pgtabl: 'alyf_asvs'
  pgport: 5432

keys:
  openAI: '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'
  google: 'AIzaSyB88bY1dmo50Pp9dSTzln-JqhsfV_CSW2o'
  search_engine: '336ee76d0d6af4acd'

action_desc:
  ada: "Ask LLM. What leads to X. What leads to Y. Hi Ada let me know what is X. LLM based query. Open ai tell me why a happens."
  semantic_search: "Perform semantic search given a query. Queries can be like find similar items"
  google_search: "Query google to find answers to certain questions. Can you use google to get me the results, look at google , get search results , get reference links, do google search."
  data_search: "Look in the table. Look in csv file. Evaluate the table. Find in table. Resolve dataframe . Write code to extract. Write queries to. Show me the results of a particular entity. Get me the list of entities where val > X. Analyse the data in a particular time period."

schema:
  alyf_asvs:
    keys:
      - "cardio_recovery_time_daily_avg"
      - "timestamp"
      - "heart_rate_daily_avg"
      - "heart_rate_daily_max"
      - "weight_daily_avg"
      - "hrv_daily_min"
      - "spo2_daily_avg"
      - "breathing_rate_daily_avg"
      - "sleep_duration_total_daily_sum"
      - "hypnogram_daily_avg"
      - "step_count_daily_max"
      - "vo2_max_daily_max"
      - "weight_daily_avg_1d_delta_v"
      - "weight_daily_avg_3d_delta_v"
      - "weight_daily_avg_7d_delta_v"
      - "weight_daily_avg_90d_delta_v"
      - "daily_hfi"
      - "mindfulness_minutes_daily_sum"
      - "bp_systolic_daily_max"
      - "bp_systolic_daily_avg"
      - "bp_diastolic_daily_avg"
      - "bp_diastolic_daily_min"
      - "idling_heart_rate_daily_avg"
      - "idling_heart_rate_daily_max"
      - "member_id"
    dataTypes:
      - "double precision"
      - "timestamp with time zone"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "double precision"
      - "character varying"
    descriptors:
  alyf_members:
    keys:
      - "active"
      - "tryv_info"
      - "create_time"
      - "update_time"
      - "date_of_birth"
      - "synth"
      - "gender"
      - "address"
      - "member_id"
      - "fallback_time_zone"
      - "provider_id"
      - "first_name"
      - "last_name"
      - "email"
      - "tryv_id"
    dataTypes:
      - "boolean"
      - "jsonb"
      - "timestamp with time zone"
      - "timestamp with time zone"
      - "timestamp with time zone"
      - "boolean"
      - "character varying"
      - "character varying"
      - "character varying"
      - "character varying"
      - "character varying"
      - "character varying"
      - "character varying"
      - "character varying"
      - "character varying"
    descriptors: